recipe: default.v1
language: en
pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 100
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
- name: FallbackClassifier
  nlu_threshold: 0.4
  core_threshold: 0.4
  fallback_action_name: "action_custom_fallback"


policies:
- name: RulePolicy
  nlu_fallback_threshold: 0.3
  core_fallback_threshold: 0.3
  core_fallback_action_name: "action_custom_fallback"
  nlu_fallback_action_name: "action_custom_fallback"
  enable_fallback_prediction: True
- name: MemoizationPolicy
- name: TEDPolicy
  max_history: 5
  epochs: 100
assistant_id: nevrio-bot

